#!/bin/sh

# Copyright (2020) by Marcel Lambert.
# This project is dual licensed under either MIT or Apache-2.0.

set -e

echo '+cargo fmt'
cargo fmt --all -- --check
echo '+cargo test --all'
cargo test --all
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings

