#!/bin/sh

# Copyright (2020) by Marcel Lambert
# This project is licensed under the Hippocratic License.
# See LICENSE.md for more information

set -e

echo '+cargo fmt'
cargo fmt --all -- --check
echo '+cargo test --all'
cargo test --all
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings


## check outdated dependencies
cargo outdated --root-deps-only --exit-code -1
cargo outdated --root-deps-only --manifest-path uuid-macro/cargo.toml
cargo outdated --root-deps-only --manifest-path uuid-macro-hack/cargo.toml