#!/bin/sh

# Copyright (2020) by Marcel Lambert.
# This project is dual licensed under either MIT or Apache-2.0.

set -e

if grep "^[^#;]" $1
    then 
        echo "commit message provided, skipping default"      
    else 
        printf "$(cat commitmessage)\n$(cat $1)" > $1
fi