#!/bin/sh

set -e

export CARGO_INCREMENTAL=0
cargo build

echo '+cargo fmt'
cargo fmt --all -- --check

echo '+cargo test --all'
#cargo test --all --no-fail-fast --quiet

echo '+cargo clippy --all -- -D warnings'
#cargo clippy --all -- -D warnings

# check licences of dependencies are valid
echo '+lichking check'
cargo lichking check
cd uuid-macro
cargo lichking check
cd ../uuid-macro-hack
cargo lichking check
cd ../