policies:
  - type: commit
    spec:
      headerLength: 89
      dco: false
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: false
      conventional:
        types:
          - "build"
          - "ci"
          - "docs"
          - "feat"
          - "fix"
          - "perf"
          - "refactor"
          - "style"
          - "test"
        scopes:
          - "generic"
          - "native"
          - "cocoa"
          - "mock"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - target/
      includeSuffixes:
        - .rs
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        /*
         * Copyright (2020) by Marcel Lambert.
         * This project is dual licensed under either MIT or Apache-2.0.
         */