#![allow(incomplete_features)]
#![feature(generic_associated_types)]
#![warn(missing_debug_implementations, missing_docs)]

//! Helper crate to create the default_widgets macro.
//!
//! You should not need this crate directly. The macro is reexported in
//! 'plating_systems'. Use it from there instead.


use plating_systems_macros::build_widget_list;


build_widget_list! {
    /// The list of default widgets.
    ///
    /// Used by several system macros to reduce copy & pasting a list of all supported widgets by plating.
    ///
    /// Autogenerated by 'build_widget_list'. Look there if you want to customize your own List of widgets.
    default_widgets = {
        /// The Window type used by plating
        type Window<OUTLET: OutletHolder
                          + Outlet<MenuOutlet>
                          + Outlet<ChildrenOutlet>>: Window<OUTLET>;
        /// The button type used by plating
        type Button<OUTLET: OutletHolder>: Button<OUTLET>;
    };
}
