name: Conform Check
on:
  push:
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Conform Action
            uses: talos-systems/conform@v0.1.0-alpha.19
