name: Dependencies

env:
  CARGO_TERM_COLOR: always

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/daily_audit_check.yml'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/daily_audit_check.yml'
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-outdated
      - name: Outdated dependencies
        uses: actions-rs/cargo@v1
        with:
          command: outdated
          args: --root-deps-only --exit-code -1